# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_multiplication_cpp <- function(x, y, tx = FALSE, ty = FALSE, cores = 1L) {
    .Call(`_ClusterDE_matrix_multiplication_cpp`, x, y, tx, ty, cores)
}

